# Generated by Django 4.0.6 on 2022-07-29 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('short_description', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='static/img/club_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_since', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_in_bureau', models.BooleanField(default=False)),
                ('is_president', models.BooleanField(default=False)),
                ('poste', models.CharField(choices=[('président', 'Président'), ('secrétaire', 'Secrétaire'), ('trésorier', 'Trésorier'), ('membre', 'Membre'), ('respo comm', 'Responsable communication'), ('vice-président', 'Vice-président'), ('respo partenariats', 'Responsable partenariats')], default='membre', max_length=64)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='student_life.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
